dist: xenial

language: python
python:
    - "2.7"
addons:
    postgresql: '11'
    apt:
        packages:
            - postgresql-11
            - postgresql-client-11
env:
    global:
        - PGPORT=5433
        - CKANVERSION=2.8
install:
    - bash bin/travis-build.bash
services:
    - redis
script: sh bin/travis-run.sh
after_success: coveralls
sudo: required
cache:
  directories:
    - $HOME/.cache/pip
